### ISSUE TITLE
Typo in `f_str()` documentation on valid variables

### ISSUE THREAD

**Issue by mstackhouse** [atorus-research/Tplyr#101]
`f_str()` docs say 'variance' instead of 'var' for the variance summary in desc layers.

https://github.com/atorus-research/Tplyr/blob/03f7650d932fd2fb5b9609c77ac6b220c991a0c7/R/format.R#L83

**Comment by mstackhouse** [comment]
This should distinctly say `var`, not `variance`.

**Comment by mstackhouse** [comment]
Well darn this appears in the vignette too:

https://github.com/atorus-research/Tplyr/blob/03f7650d932fd2fb5b9609c77ac6b220c991a0c7/vignettes/desc.Rmd#L64

**Comment by sadchla-codes** [comment]
I'll do a walkthrough and change it everywhere applicable.

**Comment by sadchla-codes** [comment]
@mstackhouse it seems like **variance** shows up in a lot of other files so I would like to read over the different files to see if there are instances where `variance` is meant to be used instead of `var` to make sure I don't accidently replace all of them if it's not applicable
![variance](https://user-images.githubusercontent.com/112789549/197863140-394608f9-e6e8-44ac-b58c-470bee8814fa.png)

**Comment by mstackhouse** [comment]
@sadchla-codes Only the ones I've noted in the issue need to be changed - so no other situations in that screenshot are problems. Thanks for the thorough investigation!

**Comment by sadchla-codes** [comment]
okay, got it!
